version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: nexstore_db
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: nexstore
      POSTGRES_PASSWORD: Qwert.12345
      POSTGRES_DB: nexstore_db
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data: